services:
  backend:
    image: ${DOCKERHUB_USERNAME}/message-service:latest
    ports:
      - ${PORT_BACKEND}:8080
    command: /app/main
    restart: always
    depends_on:
      - mongo
    environment:
      - MONGODB_URI=mongodb://${MONGO_ROOT_USERNAME}:${MONGO_ROOT_PASSWORD}@mongo:27017/botgo.mod?authSource=admin
      - MONGODB_NAME=bot_profile_manager
      - SERVER_ADDRESS=:8080
      - TZ=Asia/Tokyo
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 512M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  mongo:
    image: mongo:5.0
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD}
    restart: always
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  mongo_data: