openapi: 3.0.0
info:
  title: ボットプロフィール管理API
  version: 1.0.0
  description: ボットのプロフィール情報を管理するためのAPI

paths:
  /bot/{botId}/profile:
    put:
      summary: ボットのプロフィールを登録または更新する
      parameters:
        - name: botId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Profile"
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"
        "400":
          description: 不正なリクエスト
        "500":
          description: サーバーエラー

    get:
      summary: ボットのプロフィールを取得する
      parameters:
        - name: botId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: 成功
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Profile"
        "404":
          description: ボットが見つかりません
        "500":
          description: サーバーエラー

components:
  schemas:
    Profile:
      type: object
      required:
        - name
        - personality
      properties:
        name:
          type: string
          description: ボットの名前
        personality:
          type: string
          description: ボットの性格の説明
        avatar:
          type: string
          description: ボットのアバター画像URL（オプション）
        language:
          type: string
          description: ボットの使用言語（オプション）
        createdAt:
          type: string
          format: date-time
          description: プロフィール作成日時
        updatedAt:
          type: string
          format: date-time
          description: プロフィール更新日時
